services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE: ${IMAGE}
        RELEASE: ${RELEASE}
        USER_NAME: ${USER_NAME}
    container_name: python
    hostname: python
    working_dir: /home/${USER_NAME}/python
    command: /bin/bash -lc "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /home/${USER_NAME}/python
      - type: bind
        source: ./commandhistory
        target: /home/${USER_NAME}/commandhistory
